### ISSUE TITLE
When sending multiple email blocks, check for negative time span.

### ISSUE THREAD

**Issue by jeffreykirchner** [jeffreykirchner/ESIMassEmailerMS#32]

**Comment by jeffreykirchner** [comment]
Traceback (most recent call last):
  File "/tmp/8db7e643dd5a02d/antenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8db7e643dd5a02d/antenv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8db7e643dd5a02d/antenv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8db7e643dd5a02d/antenv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8db7e643dd5a02d/antenv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8db7e643dd5a02d/antenv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/tmp/8db7e643dd5a02d/antenv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/tmp/8db7e643dd5a02d/antenv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8db7e643dd5a02d/main/views/send_email.py", line 36, in post
    result = take_and_send_incoming_email(request.user, request.data, settings.DEBUG)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8db7e643dd5a02d/main/views/send_email.py", line 94, in take_and_send_incoming_email
    time.sleep(sleep_length-time_span.total_seconds())
